site_name: My Docs
theme:
  name: material
  language: 'ja'

extra:
    search:
        language: 'jp'

## ナビゲーションバー
nav:
  - Home: index.md
  - About:
    - About: about.md
    - mypage: mypage.md

## Markdown を正しく表示させるための設定
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
          
copyright: Copyright &copy; 2024 , Hogehoge .
